# Generated by Django 4.1.7 on 2023-02-21 05:33

import apps.diplomas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferredDegree",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_kk",
                    models.CharField(
                        max_length=255, verbose_name="Название на казахском"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, verbose_name="Название на английском"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, verbose_name="Название на русском"
                    ),
                ),
            ],
            options={
                "verbose_name": "Присваемая степень",
                "verbose_name_plural": "Присваемые степени",
            },
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_kk",
                    models.CharField(
                        max_length=255, verbose_name="Название на казахском"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, verbose_name="Название на английском"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, verbose_name="Название на русском"
                    ),
                ),
            ],
            options={
                "verbose_name": "Степень",
                "verbose_name_plural": "Степени",
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_kk",
                    models.CharField(
                        max_length=150, verbose_name="Название на казахском"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=150, verbose_name="Название на английском"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=150, verbose_name="Название на русском"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, verbose_name="Код специальности"),
                ),
                (
                    "is_educational_program",
                    models.BooleanField(
                        default=True,
                        help_text="Если True - образовательная программа, иначе - специальность",
                        verbose_name="Образовательная программа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальности",
            },
        ),
        migrations.CreateModel(
            name="StudyForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_kk",
                    models.CharField(
                        max_length=150, verbose_name="Название на казахском"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=150, verbose_name="Название на английском"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=150, verbose_name="Название на русском"
                    ),
                ),
            ],
            options={
                "verbose_name": "Форма обучения",
                "verbose_name_plural": "Формы обучения",
            },
        ),
        migrations.CreateModel(
            name="Diploma",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iin",
                    models.CharField(
                        db_index=True, max_length=30, unique=True, verbose_name="ИИН"
                    ),
                ),
                (
                    "firstname_kk",
                    models.CharField(
                        max_length=255, verbose_name="Имя на казахском (в дат. падеже)"
                    ),
                ),
                (
                    "lastname_kk",
                    models.CharField(
                        max_length=255,
                        verbose_name="Фамилия на казахском (в дат. падеже)",
                    ),
                ),
                (
                    "patronymic_kk",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Отчество на казахском (в дат. падеже)",
                    ),
                ),
                (
                    "firstname_en",
                    models.CharField(max_length=255, verbose_name="Имя на английском"),
                ),
                (
                    "lastname_en",
                    models.CharField(
                        max_length=255, verbose_name="Фамилия на английском"
                    ),
                ),
                (
                    "firstname_ru",
                    models.CharField(
                        max_length=255, verbose_name="Имя на русском (в дат. падеже)"
                    ),
                ),
                (
                    "lastname_ru",
                    models.CharField(
                        max_length=255,
                        verbose_name="Фамилия на русском (в дат. падеже)",
                    ),
                ),
                (
                    "patronymic_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Отчество на русском (в дат. падеже)",
                    ),
                ),
                (
                    "is_honors",
                    models.BooleanField(
                        default=False, verbose_name="Димлоп с отличием"
                    ),
                ),
                (
                    "protocol_number",
                    models.CharField(max_length=100, verbose_name="Номер протокола"),
                ),
                (
                    "protocol_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата подписания протокола заседания аттестационной комиссии",
                    ),
                ),
                (
                    "diploma_number",
                    models.CharField(
                        max_length=100, verbose_name="Серия и номер диплома"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата выдачи диплома"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=32, verbose_name="Регистрационный номер диплома"
                    ),
                ),
                (
                    "qr",
                    models.FileField(
                        upload_to=apps.diplomas.models.diploma_directory_path,
                        verbose_name="Файл QR",
                    ),
                ),
                (
                    "docx",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.diplomas.models.diploma_directory_path,
                        verbose_name="Файл диплома (DOCX)",
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.diplomas.models.diploma_directory_path,
                        verbose_name="Файл диплома (PDF)",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "conferred_degree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="diplomas.conferreddegree",
                        verbose_name="Присваемая степень",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="diplomas.specialty",
                        verbose_name="Специальность / ОП",
                    ),
                ),
                (
                    "study_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="diplomas.studyform",
                        verbose_name="Форма обучения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Диплом",
                "verbose_name_plural": "Дипломы",
            },
        ),
        migrations.AddField(
            model_name="conferreddegree",
            name="degree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="diplomas.degree",
                verbose_name="Степень",
            ),
        ),
    ]
