# Generated by Django 4.1.7 on 2023-02-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("diplomas", "0004_alter_studyform_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conferreddegree",
            name="degree",
        ),
        migrations.AddField(
            model_name="diploma",
            name="degree",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="diplomas.degree",
                verbose_name="Степень",
            ),
            preserve_default=False,
        ),
    ]
