# Generated by Django 4.1.7 on 2023-02-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diplomas", "0005_remove_conferreddegree_degree_diploma_degree"),
    ]

    operations = [
        migrations.AddField(
            model_name="diploma",
            name="platonus_id",
            field=models.IntegerField(
                db_index=True, null=True, verbose_name="ID аккаунта Platonus"
            ),
        ),
    ]
