# Generated by Django 4.1.7 on 2023-02-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diplomas", "0006_diploma_platonus_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialty",
            name="platonus_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ID в Platonus"
            ),
        ),
    ]
