# Generated by Django 4.1.7 on 2023-03-09 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diplomas", "0007_specialty_platonus_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDiploma",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "platonus_id",
                    models.IntegerField(
                        db_index=True, null=True, verbose_name="ID аккаунта Platonus"
                    ),
                ),
                (
                    "iin",
                    models.CharField(db_index=True, max_length=30, verbose_name="ИИН"),
                ),
                (
                    "firstname_kk",
                    models.CharField(
                        max_length=255, verbose_name="Имя на казахском (в дат. падеже)"
                    ),
                ),
                (
                    "lastname_kk",
                    models.CharField(
                        max_length=255,
                        verbose_name="Фамилия на казахском (в дат. падеже)",
                    ),
                ),
                (
                    "patronymic_kk",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Отчество на казахском (в дат. падеже)",
                    ),
                ),
                (
                    "firstname_en",
                    models.CharField(max_length=255, verbose_name="Имя на английском"),
                ),
                (
                    "lastname_en",
                    models.CharField(
                        max_length=255, verbose_name="Фамилия на английском"
                    ),
                ),
                (
                    "firstname_ru",
                    models.CharField(
                        max_length=255, verbose_name="Имя на русском (в дат. падеже)"
                    ),
                ),
                (
                    "lastname_ru",
                    models.CharField(
                        max_length=255,
                        verbose_name="Фамилия на русском (в дат. падеже)",
                    ),
                ),
                (
                    "patronymic_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Отчество на русском (в дат. падеже)",
                    ),
                ),
                (
                    "is_honors",
                    models.BooleanField(
                        default=False, verbose_name="Диплом с отличием"
                    ),
                ),
                (
                    "protocol_number",
                    models.CharField(max_length=100, verbose_name="Номер протокола"),
                ),
                (
                    "protocol_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата подписания протокола заседания аттестационной комиссии",
                    ),
                ),
                (
                    "diploma_number",
                    models.CharField(
                        max_length=100, verbose_name="Серия и номер диплома"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата выдачи диплома"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=32, verbose_name="Регистрационный номер диплома"
                    ),
                ),
                ("qr", models.TextField(max_length=100, verbose_name="Файл QR")),
                (
                    "docx",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Файл диплома (DOCX)",
                    ),
                ),
                (
                    "pdf",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Файл диплома (PDF)",
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, editable=False)),
                ("date_updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "conferred_degree",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="diplomas.conferreddegree",
                        verbose_name="Присваемая степень",
                    ),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="diplomas.degree",
                        verbose_name="Степень",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="diplomas.specialty",
                        verbose_name="Специальность / ОП",
                    ),
                ),
                (
                    "study_form_or_direction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Форма обучения для бакалавриата, направление для магистратуры",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="diplomas.studyform",
                        verbose_name="Форма обучения или направление",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="diplomas.diplomatemplate",
                        verbose_name="Шаблон диплома",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Диплом",
                "verbose_name_plural": "historical Дипломы",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
