# Generated by Django 4.1.7 on 2023-03-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diplomas", "0008_historicaldiploma"),
    ]

    operations = [
        migrations.AddField(
            model_name="diploma",
            name="status",
            field=models.CharField(
                choices=[
                    ("generated", "Сгенерирован"),
                    ("ready", "Готов к печати"),
                    ("printed", "Распечатан"),
                ],
                default="generated",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="historicaldiploma",
            name="status",
            field=models.CharField(
                choices=[
                    ("generated", "Сгенерирован"),
                    ("ready", "Готов к печати"),
                    ("printed", "Распечатан"),
                ],
                default="generated",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
    ]
